Repository quarkslab/qbindiff, pull requests merged in 2023-11, with the labels that each got.

#42 Small fix identified after testing
  src/qbindiff/differ.py
  src/qbindiff/passes/passes.py
Labels: bug, high

#38 add custom anchoring
  src/qbindiff/passes/__init__.py
  src/qbindiff/passes/passes.py
Labels: enhancement

#43 [binexport] Refactor ISA guessing heuristic
  src/qbindiff/loader/backend/binexport.py
  src/qbindiff/utils/__init__.py
  src/qbindiff/utils/utils.py
Labels: refactoring
